# Generated by Django 4.0.6 on 2022-08-11 14:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=600)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='img')),
            ],
        ),
    ]
